# Generated by Django 5.2.4 on 2025-07-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('stars', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('3-5', '3-5'), ('6-8', '6-8'), ('9-12', '9-12')], max_length=10)),
                ('easy_preview', models.ImageField(blank=True, null=True, upload_to='drawings/')),
                ('easy_coordinates', models.JSONField(default=list)),
                ('medium_preview', models.ImageField(blank=True, null=True, upload_to='drawings/')),
                ('medium_coordinates', models.JSONField(default=list)),
                ('hard_preview', models.ImageField(blank=True, null=True, upload_to='drawings/')),
                ('hard_coordinates', models.JSONField(default=list)),
                ('current_dot', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon_path', models.CharField(max_length=200)),
                ('earned_by', models.ManyToManyField(blank=True, related_name='achievements', to='api.user')),
            ],
        ),
    ]
