# Generated by Django 5.2.4 on 2025-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/input/'),
        ),
    ]
