# Generated by Django 5.2.4 on 2025-07-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_drawing_input_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='age_group',
        ),
    ]
