# Generated by Django 5.2.4 on 2025-07-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_drawing_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='line_image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/lines/'),
        ),
    ]
