# Generated by Django 5.2.4 on 2025-07-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_drawing_line_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='is_completed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drawing',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
