# Generated by Django 5.2.4 on 2025-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_drawing_is_completed_drawing_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='easy_preview',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='hard_preview',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='line_image',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='medium_preview',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='progress',
        ),
        migrations.AddField(
            model_name='drawing',
            name='easy_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/draw_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='easy_learn_coordinates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drawing',
            name='easy_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/learn_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='hard_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/draw_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='hard_learn_coordinates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drawing',
            name='hard_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/learn_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='medium_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/draw_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='medium_learn_coordinates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='drawing',
            name='medium_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/learn_'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='outline_image',
            field=models.ImageField(blank=True, null=True, upload_to='lines/'),
        ),
    ]
