# Generated by Django 5.2.4 on 2025-07-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_drawing_easy_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='easy_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/easy'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='easy_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/easy'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/hard'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/hard'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='draw/medium'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='learn/medium'),
        ),
    ]
