# Generated by Django 5.2.4 on 2025-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_drawing_easy_draw_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='easy_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/draw/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='easy_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/learn/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/draw/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/learn/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/draw/'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/learn/'),
        ),
    ]
