# Generated by Django 5.2.4 on 2025-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_drawing_easy_draw_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='is_completed',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='drawing',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='outline_image',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/lines/'),
        ),
    ]
