# Generated by Django 5.2.4 on 2025-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_drawing_is_completed_drawing_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='easy_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='easy_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='hard_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_draw_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='medium_learn_preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='outline_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
